# https://hydra.cc/docs/configure_hydra/intro/

# 启用彩色日志
defaults:
  - override hydra_logging: colorlog
  - override job_logging: colorlog

# 输出目录，每次运行时动态生成
run:
  dir: ${paths.log_dir}/${task_name}/runs/${id}
sweep:
  dir: ${paths.log_dir}/${task_name}/multiruns/${id}
  subdir: ${hydra.job.num}

job_logging:
  handlers:
    file:
      # 合并了 https://github.com/facebookresearch/hydra/pull/2242 的修复
      filename: ${hydra.runtime.output_dir}/${task_name}.log
