# 根目录路径
# 需要存在 PROJECT_ROOT 环境变量
# 如果希望根目录为当前工作目录，可替换为 "."
root_dir: .

# 数据目录路径
data_dir: ???

# 日志目录路径
log_dir: ${paths.root_dir}/logs
# 输出目录路径，由 Hydra 动态创建
# 路径生成模式在 `configs/hydra/default.yaml` 中指定
# 用于存储运行期间生成的所有文件，如检查点和指标
output_dir: ${hydra:runtime.output_dir}

# 工作目录路径
work_dir: ${hydra:runtime.cwd}

# 我们将 profile_dir 定义为与 output_dir 不同的路径，
# 因为分析器不支持 GCS 路径。运行结束后，我们会将
# 分析器输出复制到 output_dir
profile_dir: ${hydra:run.dir}/profile_output

# 用于作业失败时重试的元数据路径
metadata_dir: ${paths.output_dir}/metadata
