## EarlyStopping 用于在监控指标不再改善时停止训练。
## 实现了 https://lightning.ai/docs/pytorch/stable/api/lightning.pytorch.callbacks.EarlyStopping.html 的回调

early_stopping:
  _target_: lightning.pytorch.callbacks.EarlyStopping
  monitor: ??? # 要监控的指标，必须指定！！！
  min_delta: 0. # 监控指标的最小变化量，以判定为改善
  patience: 3 # 在多少次检查无改善后停止训练
  verbose: False # 详细模式
  mode: "min" # "max" 表示指标值越高越好，也可以是 "min"
  strict: True # 如果在验证指标中找不到监控指标是否崩溃
  check_finite: True # 设为 True 时，当监控指标变为 NaN 或无穷大时停止训练
  stopping_threshold: null # 当监控指标达到此阈值时立即停止训练
  divergence_threshold: null # 当监控指标变得比此阈值更差时立即停止训练
  check_on_train_epoch_end: null # 是否在训练 epoch 结束时运行早停
  # log_rank_zero_only: False  # 此关键字参数在稳定版本中不可用
