## 推理回调，将预测结果写入本地 pickle 文件
pickle_writer:
  _target_: src.utils.inference_utils.LocalPickleWriter
  output_dir: ${paths.output_dir}/pickle
  flush_frequency: 100000
  write_interval: batch
  should_merge_files_on_main: True
