## 在控制台打印模型摘要的回调。
## 实现了 https://lightning.ai/docs/pytorch/stable/api/lightning.pytorch.callbacks.RichModelSummary.html 的回调

model_summary:
  _target_: lightning.pytorch.callbacks.RichModelSummary
  max_depth: 1 # 摘要将包含的层嵌套最大深度
