## 保存最佳分数模型的回调。
## 实现了 https://lightning.ai/docs/pytorch/stable/api/lightning.pytorch.callbacks.ModelCheckpoint.html 的回调

model_checkpoint:
  _target_: lightning.pytorch.callbacks.ModelCheckpoint
  dirpath: null # 保存模型文件的目录
  filename: null # 检查点文件名
  monitor: null # 用于判断模型是否改善的日志指标名称
  verbose: True # 详细模式
  save_last: null # 额外始终保存最后一个检查点的精确副本到 last.ckpt 文件
  save_top_k: 1 # 保存 k 个最佳模型（由上述指标决定）
  mode: "min" # "max" 表示指标值越高越好，也可以是 "min"
  auto_insert_metric_name: True # 为 True 时，检查点文件名将包含指标名称
  save_weights_only: False # 为 True 时，仅保存模型权重
  every_n_train_steps: null # 检查点之间的训练步数
  train_time_interval: null # 在指定时间间隔监控检查点
  every_n_epochs: null # 检查点之间的 epoch 数
  save_on_train_epoch_end: null # 是否在训练 epoch 结束或验证结束时运行检查点保存
